# docker-compose.yml
version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp_user
      POSTGRES_PASSWORD: webapp_password
